### PR TITLE
fix multi enumeration bug

### PR DESCRIPTION
**Pull request by SimonCropp**

### CODE REVIEW

**Review by martincostello — COMMENTED** [review]
Nice catch. Would you mind adding a unit test for the bug please?

**Comment by SimonCropp** [comment]
is there a test that passes multiple items ?

**Comment by martincostello** [comment]
Doesn't look like it, which I guess is why the bug you've found is there.

The templating tests are here: https://github.com/justeat/httpclient-interception/blob/cbe05bf80a1a06c8086482c04393bc174b958ac2/tests/HttpClientInterception.Tests/Bundles/BundleExtensionsTests.cs#L168-L241

**Comment by SimonCropp** [comment]
i dont have adequate understanding of this library to produce a test for this bug. but if u have a forward only enumerator (eg from a method that yields), and you have multiple `bundle.Items`, then `BundleItemConverter.FromItem` will move the enumerator  multiple times. eg if u have 1 `templateValues` and 2 `bundle.Items`, then `BundleItemConverter.FromItem` will only get the 1 templateValues on the first call. the second call to FromItem the enumerator  will be empty

**Comment by martincostello** [comment]
So this is a bug you found purely from reading the code, rather than you trying to do something specific with it and it throwing an exception?

**Comment by SimonCropp** [comment]
> So this is a bug you found purely from reading the code

resharper highlighted it as an error

**Review by martincostello — APPROVED** [review]

**Pull request merged**
