### PR TITLE
Build net461 on macOS

### PR DESCRIPTION
**Pull request by slang25**
Alternative to https://github.com/justeat/httpclient-interception/pull/47

### CODE REVIEW

**Comment by slang25** [comment]
Hmmm, that's not what we want right

**Comment by martincostello** [comment]
So with this, if you make the changes here https://github.com/justeat/httpclient-interception/pull/47#issuecomment-426915694 then it should still pass.

**Comment by martincostello** [comment]
I think Travis CI is having an issue building in parallel or something because it's complaining about file locks.

**Comment by slang25** [comment]
Looks like travis is a bit wobbly, not sure what's going on

**Comment by martincostello** [comment]
I did do a rebuild using the Retry button a few times in Travis, but it didn't help.

**Comment by martincostello** [comment]
@slang25 Something is definitely up in Travis CI.

https://travis-ci.org/justeat/httpclient-interception/jobs/437121526#L572

**Comment by martincostello** [comment]
It might be that the tests in build.sh need to be explicitly told to run for `netcoreapp2.1` now. I've had similar issues with BenchmarkDotNet where is sits doing nothing for ages, and then says there's too many TFMs and I need to pick one.

**Comment by slang25** [comment]
Dammit Travis!

**Comment by slang25** [comment]
@martincostello I'm going to build a package that takes care of this stuff, so that it's a one-liner for people in future.

To consume it you'd need to add it to your sdks like this:
```xml
<Project Sdk="Microsoft.NET.Sdk;MyPackageName">
```

Help me name this thing. `Community.NET.Sdk.FullFrameworkReferenceAssemblies` is too long. Any suggestions?

**Comment by martincostello** [comment]
`Community.Sdk.DesktopTargeting`?

**Comment by martincostello** [comment]
I've done #51 for now as I'm just prepping doing a `1.2.2` to release a change that's been sitting around in master for a while, but can merge this change at some point once this is working.

**Comment by martincostello** [comment]
I'm going to close this as it's been a while, #51 addressed this to some degree, and now there's a merge conflict.

**Pull request closed without merging**
